### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by adamgeddon1686** [HighwayWu/LASTED#10]
Sorry I am very new to this but I was quiet interested in your repository and how it works. After several attempts I think I have a version of it  that works, sort of, on windows. But while experimenting, I noticed that the files don't seem to do what I thought they did. Correct me if I am wrong but this is more of an training script that the inference using your pretrained model, correct? 

If I am missing something please let me know. I would love to use this to try and indentify synthetic images from a set of real ones to test it out but I am not sure I exactly know how. Let me know if you have time to discuss this. I appreciate your work!

**Comment by HighwayWu** [comment]
Thanks for your asking and sorry for the late replay. This repo can be used for inference, i.e., detecting the synthetic images from a set of real ones. Please follow the Usage. 3.
