### ISSUE TITLE
I try to train the model using code and the code has some errors

### ISSUE THREAD

**Issue by zj56** [HighwayWu/LASTED#11]
python3 main.py \
    --model 'LASTED' \
    --train_file 'annotation/Test_num1047.txt' \
    --num_class 4 \
    --val_ratio 0.005 \
    --test_file 'annotation/Test_num410.txt' \
    --isTrain 1 \
    --lr 0.0001 \
    --data_size 448 \
    --batch_size 48 \
    --gpu '0,1,2,3' \
    2>&1 | tee weights/log.log
<img width="805" alt="20240302_094543" src="https://github.com/HighwayWu/LASTED/assets/70707877/b853bf74-ccdd-403b-a8c7-1f46756df355">

**Comment by HighwayWu** [comment]
Thanks for your asking. Accoding to the error, the input should be 4D tensor, which means the [48, 1, 3, 448, 448] => [48, 3, 448, 448].
