### ISSUE TITLE
Some question for rerun the code

### ISSUE THREAD

**Issue by ttttsjjjj** [HighwayWu/LASTED#12]
Hello ,i am new in research.I have already set all the settings through READ ME file.But when i run the code by "sh main.sh" some problems occurs:DataParallel' object has no attribute 'data_root' .Here are my settings in main.sh:
python main.py \
    --model 'LASTED' \
    --train_file 'annotation/Train_Photos_num199244.txt' \
    --num_class 2\
    --val_ratio 0.005 \
    --test_file 'annotation/Test_MidjourneyV5_num2000.txt' \
    --isTrain 1 \
    --lr 0.0001 \
    --resume '' \
    --data_size 448 \
    --batch_size 6\
    --gpu '1,2' \
    2>&1 | tee weights/log.log
If I miss something please make me know .Thank you !

**Comment by HighwayWu** [comment]
Thanks for your asking. By default, all the images should be placed in the 'data/' folder, which is also the default 'data_root'. Also, please provide a more detailed error screenshot for analyzing.

**Comment by ttttsjjjj** [comment]
Thanks for your reply!Here are my training images in the 'data/'folder,(i just use the dataset'RealPhoto_LSUN'and 'SyntheticPhoto_ProGAN' for training)
![image](https://github.com/HighwayWu/LASTED/assets/151114315/5e8283ec-4e3e-4193-b577-a154075a8ae3)

Also i have prepared the training txt file named "Train_Photos_num199244" under the folder"annotation"through preprocess.py.
![image](https://github.com/HighwayWu/LASTED/assets/151114315/682eb257-b8d3-47da-9a29-fbb89a15f444)

Then i set the main.sh file  like this:
![image](https://github.com/HighwayWu/LASTED/assets/151114315/adc46fa5-c1d6-466f-afc5-2611817595ce)

Finally,i run this code by "sh main.sh"in the terminal.But some problems occurs:
![image](https://github.com/HighwayWu/LASTED/assets/151114315/aa1dabeb-43d1-49b8-838e-fd9a9eb2f8ec)
If i miss something please tell me.Thank you again for taking the time to reply !

**Comment by HighwayWu** [comment]
Sorry for the inconvenience. The reason is that the "model" was incorrectly read as "args" in [line](https://github.com/HighwayWu/LASTED/blob/11010601b2aeb3a700f0f97cb34be050eec30eca/main.py#L362). The error has been corrected, please refer to the new "main.py".

**Comment by ttttsjjjj** [comment]
Thank you very much for your reply, the previous issue is solved! But now a new question arises:
![image](https://github.com/HighwayWu/LASTED/assets/151114315/432222af-4d6f-4eef-ba58-aa740eda3cfe)
![image](https://github.com/HighwayWu/LASTED/assets/151114315/c3a1683f-b4bc-4f69-9052-9670263bb36e)
Looking forward for your reply. Thank you again!

**Comment by HighwayWu** [comment]
Sorry again for the inconvenience. The "images" should have only 4 dims, i.e., batch-size, channels, H, and W. The "rep" shoule be removed. Therefore, the line should be "b, C, H, W = images.shape", and there is no need to do ".reshape" in the next line. Relevant codes have been updated, and thanks for pointing out this issue.

**Comment by ttttsjjjj** [comment]
Thanks again for your reply, the previous issue is solved! But another small problem arises:
![image](https://github.com/HighwayWu/LASTED/assets/151114315/e34ed694-e96f-4f64-b980-0e398b169ba2)
(ps:You are really very helpful and your reply really helped me a lot, thank you again!)

**Comment by HighwayWu** [comment]
"val_score" was forgotten to be defined. Please correct it to a specific metric, such as "val_auc" or "val_ap".

**Comment by ttttsjjjj** [comment]
All problems solved! Thanks  a lot.
