### ISSUE TITLE
Some questions about the trainning

### ISSUE THREAD

**Issue by ttttsjjjj** [HighwayWu/LASTED#13]
Hello, may I ask what is the approximate number of epotchs for trainning the model in your experiment? I would like to use it as a reference. Thank you.

**Comment by HighwayWu** [comment]
Thanks for your asking. The training requires approximately 15,000 iterations (forward + backward), with a batch size of 48.

**Comment by ttttsjjjj** [comment]
OK! I knew. Thank you very much!
