### ISSUE TITLE
Question about training time

### ISSUE THREAD

**Issue by Woodyet** [HighwayWu/LASTED#6]
Hello agian,

You mention in the paper that you trained using 4 A100's.

We are looking to replicate your results, could you give us an idea of how long it took to train the model on your hardware?

Thanks!

**Comment by HighwayWu** [comment]
Hi, Woodyet!

The model would fully converge in about 6 hours. PS: Using pre-trained weights (ImageNet or LAION) as initialization will accelerate the convergence process.

**Comment by Woodyet** [comment]
Thanks a lot! And thanks for the pre-trained pointer :)
