### ISSUE TITLE
Training problem

### ISSUE THREAD

**Issue by LoreImbo** [HighwayWu/LASTED#8]
Hi, very nice work. I'm trying to reproduce the results on a new image dataset but I'm experiencing a blocking problem.
The problem's output is as follows:

RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 3, 3], but got 5-dimensional input of size [16, 1, 3, 448, 448] instead

I find it on line 360 of the 'main.py' file when the function 'train_one_epoch()' is called.
Do you have any idea how I can solve it?

I'm pretty sure that [16] is about batch size, because I tried editing several times; while [448,448] is the image size.

Thank you

**Comment by HighwayWu** [comment]
Thanks for your interest. The input size should be 4-dimensional tensor with [batch_size, 3, img_size, img_size]. So, just simply remove the additional dimension by using "squeeze(1)".

**Comment by LoreImbo** [comment]
Thank you so much, it worked!

**Comment by LoreImbo** [comment]
Sorry to bother, I encountered an additional error again at the same line you quote:

RuntimeError: The size of tensor a (37) must match the size of tensor b (197) at non-singleton dimension 0

Also I add some information, I am using as batch size 16, image size 200 and I am trying to classify the images into only 2 classes.
Do you have any advice for me regarding this error?

**Comment by LoreImbo** [comment]
Sorry to bother you again but I am having another problem during the training phase.
I get this error on line 204 related to the validation_cluster function:

AttributeError: 'DataParallel' object has no attribute 'data_root'
in
  File "main.py", line 204, in validation_cluster
    ImageDataset(args.data_root, test_file, data_size=args.data_size), args.batch_size, shuffle=False,

I emphasize the fact that I had to change model from RN50x64 to RN50 due to limited GPU.

Do you have any advice for me? Thank you
