### ISSUE TITLE
Please provide unzip code

### ISSUE THREAD

**Issue by yanzhelee** [HighwayWu/LASTED#9]
<img width="559" alt="image" src="https://github.com/HighwayWu/LASTED/assets/30402531/761f2b6b-22a9-49b0-bb35-50000ef63e66">

**Comment by HighwayWu** [comment]
Sorry for the inconvenience caused by this situation, it is because we are adjusting the Google Drive. Please contact our email (yc07912@um.edu.mo) to request the unzip password. Thanks.

**Comment by yanzhelee** [comment]
Sorry email could not be sent successfully。
<img width="726" alt="image" src="https://github.com/HighwayWu/LASTED/assets/30402531/9e8fe14e-3f49-46e6-9850-b73a5ddaaeda">
Please send unzip code to this email address：1508435303@qq.com

**Comment by HighwayWu** [comment]
Thank you for your patience, and the unzip code has been sent to your email.

**Comment by yanzhelee** [comment]
Thanks.

**Comment by EchoXu98** [comment]
> Thank you for your patience, and the unzip code has been sent to your email.

您好，我也遇见了发送邮箱不可达的问题，请问能否提供数据集的解压密码至我的邮箱：xl442242883@163.com。万分感谢！
